### PR TITLE
got product type links to show all products of that type

### LINKED ISSUE #45: User can view all products that are of a particular product type
**Given** the user is on any page of the Bangazon site
**When** the user performs a gesture on a product category name
**Then** a list of all products in that category will be displayed, with title, quantity, and price/unit

### PR DESCRIPTION
**Pull request by rebeccapatek**
# Description
you can click on a product type and it takes you too a list of products of that type

Fixes # (45)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests
Click on a link of product type and see the list of products

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jansenv — APPROVED** [review]
now THIS is podracing

**Comment by rebeccapatek** [comment]
What is pod-racing?

**Comment by jansenv** [comment]
> 
> 
> What is pod-racing?

https://gph.is/2pKV4S6

**Review by holdenprkr — APPROVED** [review]
Awesome stuff!

**Pull request merged**
